# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2
      - name: Yarn Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: actions/checkout@v2
      - name: Yarn Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Yarn Test
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
