# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Yarn Test
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: test
